# Generated by Django 5.0.1 on 2024-01-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
