# Generated by Django 5.0.1 on 2024-01-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_message_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='createded',
            new_name='created',
        ),
    ]
